apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentcopilot.fullname" . }}
  labels:
    {{- include "paymentcopilot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "paymentcopilot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paymentcopilot.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "paymentcopilot.serviceAccountName" . }}
      containers:
        - name: paymentcopilot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "paymentcopilot.fullname" . }}-config
            - secretRef:
                name: {{ include "paymentcopilot.secretName" . }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
