{{- if not .Values.secret.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paymentcopilot.secretName" . }}
  labels:
    {{- include "paymentcopilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
